
```{r}
#| label: setup

# import packages
suppressPackageStartupMessages({
  library(dplyr)
  library(gt)
  library(showtext)
  library(ggplot2)
  library(worldfootballR)
})

# setup fonts
sysfonts::font_add_google("Inter")
showtext::showtext_auto()

# set plot theme
# inspired by https://github.com/z3tt/TidyTuesday/blob/main/R/2020_31_PalmerPenguins.Rmd
theme_set(theme_minimal(base_size = 16, base_family = "Inter")) +
  theme_update(
    plot.background = element_rect(fill = "white", color = "white"),
    panel.grid.major = element_line(color = "grey90", linewidth = .4),
    panel.grid.minor = element_blank(),
    axis.title.x = element_text(
      color = "grey30", margin = margin(t = 10), size = rel(1.2)
      ),
    axis.title.y = element_text(
      color = "grey30", margin = margin(r = 10), size = rel(1.2)
      ),
    axis.text = element_text(color = "grey50", size = rel(1.1)),
    axis.text.y = element_text(
      colour = "grey20", size = rel(1.15), hjust = 0.5, lineheight = .4
      ),
    axis.ticks = element_line(color = "grey90", linewidth = .4),
    axis.ticks.y = element_blank(),
    axis.ticks.length = unit(.2, "lines"),
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(
      size = rel(1.1), hjust = 0, margin = margin(0, 0, 0, 5)
      ),
    legend.spacing = unit(0, "cm"),
    legend.box.spacing = unit(0.5, "cm"),
    legend.key.width = unit(2, "cm"),
    plot.title = element_text(
      hjust = 0, color = "black",
      size = rel(2), margin = margin(t = 5, b = 5)
    ),
    plot.subtitle = element_text(
      hjust = 0, color = "grey30",
      lineheight = 0.8, size = rel(1.2), 
      margin = margin(10, 0, 10, 0)
    ),
    plot.title.position = "plot",
    plot.caption = element_text(
      color = "grey50", size = rel(1.1), hjust = 1,
      margin = margin(15, 0, 0, 0)
    ),
    plot.caption.position = "plot",
    plot.margin = margin(rep(20, 4)),
    strip.text = element_text(size = rel(1.25))
  )

bvb_stats <- 
    readr::read_csv(here::here("bvb", "sahin", "data", "bvb_stats.csv")) |> 
    dplyr::mutate(
        season =
            forcats::as_factor(
                glue::glue(
                    "{season}/{as.numeric(stringr::str_sub(season, start = -2)) + 1}"
                    )
            ),
        manager = if_else(season == "2022/23", "Terzic", "Şahin") 
    )
```

```{r}

bvb_stats |> 
  summarise(across(where(is.numeric), sum), .by = manager) |> 
  mutate(
    gd = gls_for - gls_against,
    xgd = xg_for - xg_against,
    npxgd = npxg_for - npxg_against
    )
```

```{r}

bvb_stats |> 
    summarise(across(where(is.numeric), mean), .by = manager)|> 
    select(!round) |> 
    mutate(
      npxg_per_shot_for = npxg_for/shots_for,
      npxg_per_shot_against = npxg_against/shots_against
    )
```

```{r}

bvb_stats |> 
  select(manager, contains("pen_touches")) |> 
  summarise(across(where(is.numeric), mean), .by = manager)
```

```{r}

bvb_stats |> 
    mutate(
      cumulative_npxgd = cumsum(npxg_for - npxg_against),
      cumulative_gd = cumsum(gls_for - gls_against),
      cumulative_shot_diff = cumsum(shots_for - shots_against),
      .by = season
    ) |> 
    tidyr::pivot_longer(
      cols = starts_with("cumulative"),
      names_to = "metric",
      values_to = "value"      
    ) |> 
    mutate(
      metric = 
        case_when(
          metric == "cumulative_gd" ~ "Goal Difference",
          metric == "cumulative_npxgd" ~ "npxG Difference",
          metric == "cumulative_shot_diff" ~ "Shot Difference"
        )
    ) |> 
    ggplot(aes(round, value, colour = manager)) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey30", linewidth = .8, alpha = .8) +
    ggbump::geom_bump(linewidth = 1.2, smooth = 6) +
    geom_point(shape = 21, size = 5, stroke = 1.5, fill = "white") +
    scale_colour_manual(values = c("#ffa600", "#343a40")) +
    scale_x_continuous(breaks = seq(1, 12, 1)) +
    # scale_y_continuous(breaks = seq(-1, 5, 1)) +
    facet_wrap(facets = "metric", scales = "free_y", nrow = 3) +
    labs(
        title = "BVB's Goal, npxG, & Shot Differences Under Şahin & Terzic",
        subtitle = 
          stringr::str_wrap(
            glue::glue(
              "Comparing Nuri Şahin and Edin Terzic's starts to life as Borussia Dortmund ",
              "managers using cumulative goal, npxG, and shot differences over the first ",
              "12 games in the 2022/23 and 2024/25 Bundesliga seasons."
              ), width = 105,
          ),
        x = "Matchday", y = NULL,
        caption = "Visualisation: Paul Johnson  |  Data: FBref Via {worldfootballR}"
    )

ggsave(
  here::here("bvb", "sahin", "figures", "performance.png"), 
  height = 15, width = 12, dpi = 120
  )
```


```{r}

bvb_stats |> 
    mutate(
      npxgd = npxg_for - npxg_against,
      .by = season
    ) |> 
    ggplot(aes(round, npxgd, colour = manager)) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey30", linewidth = .8, alpha = .8) +
    geom_smooth(se=FALSE) +
    geom_point(shape = 21, size = 5, stroke = 1.5, fill = "white") +
    scale_colour_manual(values = c("#ffa600", "#343a40")) +
    scale_x_continuous(breaks = seq(1, 12, 1)) +
    labs(
        title = "BVB's Non-Penalty xG Difference (npxGD) Under Şahin & Terzic",
        subtitle = 
          stringr::str_wrap(
            glue::glue(
              "Comparing Nuri Şahin and Edin Terzic's starts to life as Borussia Dortmund ",
              "managers using non-penalty expected goal difference over the first 12 games ",
              "in the 2022/23 and 2024/25 Bundesliga seasons."
              ), width = 105,
          ),
        x = "Matchday", y = NULL,
        caption = "Visualisation: Paul Johnson  |  Data: FBref Via {worldfootballR}"
    )

ggsave(
  here::here("bvb", "sahin", "figures", "npxgd.png"), 
  height = 10, width = 12, dpi = 120
  )
```